export default {
  LOAD_NEWS: '@@news/LOAD_NEWS',
  LOAD_MORE_NEWS: '@@news/LOAD_MORE_NEWS',
  LOAD_PREVIEWS: '@@news/LOAD_PREVIEWS',
  LOAD_MORE_PREVIEWS: '@@news/LOAD_MORE_PREVIEWS',
  LOAD_RECAPS: '@@news/LOAD_RECAPS',
  LOAD_MORE_RECAPS: '@@news/LOAD_MORE_RECAPS'
};
